# General
log_level: DEBUG
experiment:
  model: mae
  task: finetune
  head_task: classification # regression
  # model design
  head: skip_linear  # transformer, linear, skip_linear ...
  dropout_p: 0.1
  skips: [4]
  include_raw_coordinates: False
  num_hidden_layers: 8
  file_format: blosc # h5, blosc, zarr
  transformer:
    nhead: 4
  linear:
    hidden_dim: 256
  head_input: 
    path: /mnt/local_ssd/cache # or "/mnt/sdoml" if working with images instead of embeddings
    filename: sdofm_mae_embeddings_20250811.h5 # null or '' if working with images instead of embeddings
  resuming: false # for foundation mode, be carefule with is_backbone
  backbone:
    is_backbone: false
    ckpt_dir: ./assets/check_point/backbone/AIA
    ckpt_name: null
    weights_only: false
    model: mae
    freeze: false
    unfreeze_epoch: 2
  # data
  propagation_type: wsa_time # ballistic, wsa_time
  # save condition
  downstream_model:
    resuming: false
    ckpt_dir: ./assets/check_point/classification/
    ckpt_name: null
    weights_only: false
  
# lightning trainer & callbacks
  trainer:
    accelerator: gpu # "cpu", "mps", "auto"
    devices: [0] # "auto", 1, [0, 2], etc
    strategy: auto # multi-gpu: ddp_find_unused_parameters_true, single-gpu: "auto"
    precision: 32 # "16-mixed", "32-true", "32-float", "16-mixed", etc
    profiler: simple # options are 'XLAProfiler' (TPU), 'PyTorchProfiler', warning: PyTorchProfiler only works on cpu/gpu according to docs
    max_epochs: 30 # number of epochs to train for
    log_every_n_steps: 10
    check_val_every_n_epoch: 1
    limit_train_batches: 1.0  #0.05
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    gradient_clip_val: 10
    gradient_clip_algorithm: value
    ckpt_monitor: val_loss
  

  #embedding
  #hardware condition
  seed: 0
  disable_cuda: false
  plt_style: classification/solar_wind.mplstyle
  
  wandb:
    project: hl-fdl-solar-wind-classification 
    enable: false
    entity: allshaman
    group: ""
    job_type: finetune
    tags: []
    notes: ""
    output_directory: wandb_output
    log_model: False             # can be True (final checkpoint), False (no checkpointing), or "all" (for all epoches)
    offline: true
  gcp_storage:                  # this will checkpoint all epoches and upload them to a GCP bucket, W&B will store references (TODO: perhaps explain this better)
    enabled: False
    bucket: sdofm-checkpoints
  fold: null
  evaluate: false               # skip training and only evaluate (requires checkpoint to be set)
  distributed:
    enabled: true               # set to true to use more than one device
    world_size: auto          # The "auto" option recognizes the machine you are on, and selects the appropriate number of accelerators.
    strategy: ddp_find_unused_parameters_true
# Dataset Configuration
data:  
  # if min_data and max_data are not specified, use all data
  # min/max date can change align_data (indices of sdo images) and statistics of normalization
  min_date: 2018-10-01 00:00:00    # minimum is '2010-09-09 00:00:11.08'
  max_date: 2023-12-31 23:59:59    # maximum is '2023-05-26 06:36:08.072'
  year_splits:                          # True for entire year
    train: [2019, 2020, 2021, 2022, 2023]
    val: [2019, 2020, 2021, 2022, 2023] 
    test: [2023]
  month_splits: # non selected months will form training set 
    train: [4,5,6,7,8,9,10,11,12] #[1,2,3,4,5,6,7,8,9,10] 
    val: [1,2,3]
    test: [1,2,3]
    holdout: []
  num_workers: 8               # set appropriately for your machine
  prefetch_factor: 3            # TODO: not implemented, 2 is default
  num_frames: 1 # WARNING: This is only read for FINETUNING, model num_frames overrides in BACKBONE
  drop_frame_dim: false         # Requires num_frames=1, for backwards compatibility
  in_situ:
    base_data_directory: /mnt/baobab/psp/cache/
    psp_interpolated_path: psp_interpolated_1min_labeled_zv2.zarr
    alignment_indices_path: combined_1min_2018_2023_aia.zarr #/data/label_new/combined_1min_2018_2023.zarr
    radial_norm: True
    radial_parameters: ["sc_pos_SH_r"]
    latlon_parameters: ["sc_pos_SH_lon", "sc_pos_SH_lat", "lon_footpoint", "lat_footpoint"] # , "lon_footpoint", "lat_footpoint"
    lon_cutoff: 85 # Degrees of longitude of WSA footpoint after which data is not used. Numbers larger than 90 not recommended. Set to None to turn off
  
  cadence: 1min # cadence of in-situ data, "1min", "30sec", "1h", etc 
  match_tolerance: 12 # acceptable time difference when matching the dataframe between psp and sdoml
  label_type: label_xb2015 # xb2015 (Xu and Borovsky (2015)), isax # column name: label_xb2015 in combined data
  class_names: ["Ejecta", "Coronal Hole", "Sector Reversal", "Streamer Belt"]
  instrument: psp
  under_sampling:
    ratio: [1, 1, 0.7, 0.7] #[1, 1, 0.2, 0.2] # undersample 20% of class 2 and 3.
    random_state: 1004
  
  # SDOML - SDO multi-channel data
  sdoml:
    save_directory: ./assets/
    base_directory: /mnt/baobab
    sub_directory:
      hmi: null # "HMI.zarr"  # null if you are not using it
      aia: AIA.zarr
      eve: null
      cache: cache
    components: null           # null for select all magnetic components ["Bx", "By", "Bz"]
    wavelengths: null          # null for select all wavelengths channels ["131A","1600A","1700A","171A","193A","211A","304A","335A","94A"]
    ions: null                  # null to select all ion channels ["C III", "Fe IX", "Fe VIII", "Fe X", "Fe XI", "Fe XII", "Fe XIII", "Fe XIV", "Fe XIX", "Fe XV", "Fe XVI", "Fe XVIII", "Fe XVI_2", "Fe XX", "Fe XX_2", "Fe XX_3", "H I", "H I_2", "H I_3", "He I", "He II", "He II_2", "He I_2", "Mg IX", "Mg X", "Mg X_2", "Ne VII", "Ne VIII", "O II", "O III", "O III_2", "O II_2", "O IV", "O IV_2", "O V", "O VI", "S XIV", "Si XII", "Si XII_2"]
    frequency: 12min          # smallest is 12min
    mask_with_hmi_threshold: null # None/null for no mask, float for threshold  
    apply_mask: true
    feature_engineering:
      enabled: false
      dclass: Log
    normalization:
      enabled: true
      type: log #log, zscore, min-max
      scaler_factor: 1
      scaler_div_factor: null

# model configurations
model:
  # classifier
  linear:
    d_input: 524800 # 513*512 : CLS token + [512x512] embeddings from MAE encoder block
    num_classes: 4
    max_position_element: 32
  
  # PRETRAINERS
  mae:
    img_size: 512
    patch_size: 16
    num_frames: 1
    tubelet_size: 1
    in_chans: 9 # AIA: 9 HMI: 3 ALL: 12
    embed_dim: 768
    depth: 12
    num_heads: 12
    decoder_embed_dim: 512
    decoder_depth: 8
    decoder_num_heads: 16
    mlp_ratio: 4.0
    norm_layer: LayerNorm
    masking_ratio: 0.5  #if training with images! Please check this parameter!! 0.5 from MAE_ckpt

  # ML optimization arguments:
  loss:
    use: focal # cross_entropy, focal
    focal:
      alpha: [0.45,0.35,0.1,0.1] # class weights
      gamma: 2 # down-weight easy examples
      reduction: mean #  none, mean, sum
    cross_entropy:
      class_weights: null #[0.75, 0.18, 0.04, 0.03]
  
  # for optimizer
  optimizer: 
    use: adamw
    learning_rate: 1e-4
    weight_decay: 0.05
  
  # for scheduler
  scheduler: 
    use: cosine_warmup # other options: "cosine", "plateau", "exp"
    monitor: val_loss
    cosine:
      T_max: 100
      eta_min: 1e-4
    cosine_warmup:
      total_steps: 3000
      warmup_ratio: 0.05
    plateau:
      mode: min
      factor: 0.5
      min_lr: 1e-6
      patience: 2
    exp:
      gamma: 0.95
    
  misc:
    limb_mask: true
    batch_size: 16
    accumulate_grad_batches: 16

etc:
  mpl_style: ./solar_wind.mplstyle

defaults:
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  output_subdir: null
  run:
    dir: .