# general
experiment:
  name: mae-pretrain-aia # generate random name in wandb
  project: sdofm
  model: mae
  backbone:
    model: mae
    is_backbone: true
    ckpt_dir: ../../assets/check_point/backbone/AIA/
    weight_name: null
    weights_only: false
  seed: 0
  disable_cuda: false
  
  wandb:
    enable: true
    run_id: null
    entity: allshaman
    group: ""
    job_type: pretrain
    tags: []
    notes: AIA-pretrain
    output_directory: ../assets/wandb
    log_model: False # can be True (final checkpoint), False (no checkpointing), or "all" (for all epoches)
    offline: false
  
  gcp_storage: # this will checkpoint all epoches, perhaps clean up this config
    enabled: False
    bucket: sdofm-checkpoints
  fold: null
  evaluate: false     # skip training and only evaluate (requires checkpoint to be set)
  checkpoint: null    # this is the wandb run_id of the checkpoint to load
  save_results: true  # save full results to file and wandb
  profiler: null #'XLAProfiler' # 'XLAProfiler' # options are XLAProfiler/PyTorchProfiler Warning: XLA for TPUs only works on single world size
  # lightining pretrainer
  precision: 32 #-true'       # (32, 64) for cuda, ('32-true', '16-true', 'bf16-true') for tpu
  log_every_n_steps: 50
  limit_train_batches: null
  accelerator: gpu  # options are "auto", "gpu", "tpu", "ipu", or "cpu"
  distributed:
    enabled: true
    devices: [0] # The "auto" option recognizes the machine you are on, and selects the appropriate number of accelerators.

# dataset configuration
data:
  min_date: 2010-05-01 00:00:00  # NOT IMPLEMENTED # minimum is '2010-09-09 00:00:11.08'
  max_date: 2018-12-31 23:59:59  # NOT IMPLEMENTED # maximum is '2023-05-26 06:36:08.072' '2025-07-22 23:59:59.99'
  month_splits: # non selected months will form training set 
    train: [1,2,3,4,5,6,7,8,9,10] #,2,3,4,5,6,7,8,9,10]
    val: [11]
    test: [12]
    holdout: []
  num_workers: 4    # set appropriately for your machine
  pin_memory: true
  prefetch_factor: 8
  persistent_workers: true
  num_frames: 1 # WARNING: This is only read for FINETUNING, model num_frames overrides in BACKBONE
  drop_frame_dim: false
  # output_directory: "wandb_output"
  sdoml:
    save_directory: ../../assets/
    base_directory: /mnt/baobab
    sub_directory:
      hmi: null
      aia: AIA.zarr
      eve: EVE_legacy.zarr
      cache: cache
    components: null # null for select all magnetic components ["Bx", "By", "Bz"]
    wavelengths: null # null for select all wavelengths channels ["131A","1600A","1700A","171A","193A","211A","304A","335A","94A"]
    ions: null # null to select all ion channels ["C III", "Fe IX", "Fe VIII", "Fe X", "Fe XI", "Fe XII", "Fe XIII", "Fe XIV", "Fe XIX", "Fe XV", "Fe XVI", "Fe XVIII", "Fe XVI_2", "Fe XX", "Fe XX_2", "Fe XX_3", "H I", "H I_2", "H I_3", "He I", "He II", "He II_2", "He I_2", "Mg IX", "Mg X", "Mg X_2", "Ne VII", "Ne VIII", "O II", "O III", "O III_2", "O II_2", "O IV", "O IV_2", "O V", "O VI", "S XIV", "Si XII", "Si XII_2"]
    frequency: 12min # smallest is 12min
    mask_with_hmi_threshold: null # None/null for no mask, float for threshold
    apply_mask: false
    feature_engineering:
      enabled: false
      dclass: Log
    normalization:
      enabled: true
      type: log #log, zscore, min-max
      scaler_factor: 1
      scaler_div_factor: null
      # clipping: false # this is only for log

# model configurations
model:
  # PRETRAINERS
  mae:
    img_size: 512
    patch_size: 16
    num_frames: 1
    tubelet_size: 1
    in_chans: 9
    embed_dim: 768
    depth: 12
    num_heads: 12
    decoder_embed_dim: 512
    decoder_depth: 8
    decoder_num_heads: 16
    mlp_ratio: 4.0
    norm_layer: LayerNorm
    masking_ratio: 0.5
  samae:
    # uses all parameters as in mae plus these
    masking_type: solar_aware  # 'random' or 'solar_aware'
    active_region_mu_degs: 15.73
    active_region_std_degs: 6.14
    active_region_scale: 1.0
    active_region_abs_lon_max_degs: 60
    active_region_abs_lat_max_degs: 60
  nvae:
    use_se: true
    res_dist: true
    num_x_bits: 8
    num_latent_scales: 3  # 5
    num_groups_per_scale: 1  # 16
    num_latent_per_group: 1  # 10
    ada_groups: true
    min_groups_per_scale: 1
    num_channels_enc: 30
    num_channels_dec: 30
    num_preprocess_blocks: 2   # 1
    num_preprocess_cells: 2
    num_cell_per_cond_enc: 2
    num_postprocess_blocks: 2  # 1
    num_postprocess_cells: 2
    num_cell_per_cond_dec: 2
    num_mixture_dec: 1
    num_nf: 2
    kl_anneal_portion: 0.3
    kl_const_portion: 0.0001
    kl_const_coeff: 0.0001
    # learning_rate: 1e-2
    # weight_decay: 3e-4
    weight_decay_norm_anneal: true
    weight_decay_norm_init: 1.
    weight_decay_norm: 1e-2        
    
  # FINE-TUNERS
  degragation:
    num_neck_filters: 32
    output_dim: 1 # not sure why this is implemented for autocorrelation, should be a scalar
    loss: mse # options: "mse", "heteroscedastic"
    freeze_encoder: true
    
  # ML optimization arguments:
  # for loss
  loss:
    space: patch # pixel, patch
    type: patch_weight_loss # "mae", "mse", "vector_aware_loss", "pixel_weight_loss", "huber", "patch_weight_loss"
    exclude_limb: true
    norm_pix_loss: false
    only_masked_patches: false # patch space

    pixel_weight_loss:
      base_loss: mae
      threshold: 0.3
      ar_weight_ratio: 1.0
    
    vector_aware_loss:
      base_loss: mag

    patch_weight_loss:
      base_loss:
        type: huber
        delta: 1.0
      weight_on_patches: [0.65, 0.35]

  # for optimizer
  optimizer: 
    use: adamw
    learning_rate: 3.0e-4
    weight_decay: 0.05
  
  # for scheduler
  scheduler: 
    use: cosine_warmup # other options: "cosine", "plateau", "exp"
    monitor: val_loss
    cosine:
      T_max: 100
      eta_min: 1e-6
    cosine_warmup:
      total_steps: 3000
      warmup_ratio: 0.1
    plateau:
      mode: min
      factor: 0.5
      min_lr: 1e-6
      patience: 2
    exp:
      gamma: 0.95
    
  misc:
    limb_mask: true
    epochs: 300
    batch_size: 8
    target_grad_batches: 256
    accumulate_grad_batches: 32 # accumulate grad for 32 steps

# hydra configuration
# hydra:
#   sweeper:
#     params:
#       model.mae.embed_dim: 256, 512
#       model.mae.masking_ratio: 0.5, 0.75
#       model.samae.masking_type: "random", "solar_aware"

hydra:
  run:
      dir: .